#!/system/bin/sh
# fix_brightness (LineageOS 11)
# by wangenau
#
# This script will read the brightness value from settings and set it again.
# This is a workaround for the maximum brightness issue after booting.

unset brightness

while :; do
  brightness=$(settings get system screen_brightness)

  # Break the loop if the brightness value is an integer/is initialized
  if [ "${brightness}" -eq "${brightness}" ]; then
    break
  fi

  sleep 2
done

# The screen needs a higher brightness value to update than the one that is set
settings put system screen_brightness $((${brightness} + 1))

settings put system screen_brightness ${brightness}

exit
