#!/system/bin/sh
# get_macaddrs (CyanogenMod 7)
# by subpsyke
#
# This script will read the MAC addresses from Samsung's RIL.

unset wifimac
unset btmac

# Skip processing if MAC addresses are already written
if [[ -f /data/.mac.info -a -f /data/.bt.info ]]; then
  echo "MAC addresses already found." >&2
fi

# Wait until Samsung's RIL announces MAC addresses
until [ $(expr length "${wifimac}") == 17 ]; do
  wifimac=$(getprop ril.wifi_macaddr)
  sleep 1
done

until [ $(expr length "${btmac}") == 12 ]; do
  btmac=$(getprop ril.bt_macaddr)
  sleep 1
done

# Set WiFi MAC address
echo "${wifimac}" >/data/.mac.info

# Convert BT MAC address to proper format
echo "${btmac}" \
  | sed 's!^M$!!;s!\-!!g;s!\.!!g;s!\(..\)!\1:!g;s!:$!!' >/data/.bt.info

exit
